import re
from typing import Tuple

# Common PII patterns (Aadhaar, PAN, Phone, Email, SSN)
AADHAAR_REGEX = re.compile(r'\b[2-9]{1}[0-9]{3}\s?[0-9]{4}\s?[0-9]{4}\b')
PAN_REGEX = re.compile(r'\b[A-Z]{5}[0-9]{4}[A-Z]{1}\b')
PHONE_REGEX = re.compile(r'(?:\+91[\-\s]?)?[6-9]\d{9}')
EMAIL_REGEX = re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b')
SSN_REGEX = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')

# Known jailbreak / prompt injection markers
INJECTION_MARKERS = [
    "ignore previous instructions",
    "ignore all previous instructions",
    "ignore all previous commands",
    "ignore instructions",
    "system prompt",
    "output system prompt",
    "reveal system prompt",
    "you are now DAN",
    "jailbreak",
    "act as an unfiltered AI",
    "bypass constraints",
    "reveal your prompt",
    "reveal internal instructions"
]

def mask_pii(text: str) -> str:
    """
    DPDP (Digital Personal Data Protection Act) compliance sanitizer.
    Masks sensitive identifiers before sending to third-party LLMs.
    """
    if not text:
        return text
    
    text = AADHAAR_REGEX.sub("[MASKED_AADHAAR]", text)
    text = PAN_REGEX.sub("[MASKED_PAN]", text)
    text = PHONE_REGEX.sub("[MASKED_PHONE]", text)
    text = EMAIL_REGEX.sub("[MASKED_EMAIL]", text)
    text = SSN_REGEX.sub("[MASKED_SSN]", text)
    return text

def check_prompt_injection(prompt: str) -> Tuple[bool, str]:
    """
    Checks for potential prompt injection or system override attempts.
    Returns (is_safe, sanitized_or_flag_reason)
    """
    lower_prompt = prompt.lower()
    for marker in INJECTION_MARKERS:
        if marker in lower_prompt:
            return False, f"Prompt contains restricted directive pattern: '{marker}'"
    
    if len(prompt) > 8000:
        return False, "Prompt exceeds safe maximum length"
        
    return True, "Safe"

def append_transparency_notice(response: str) -> str:
    """
    Ensures AI transparency compliance as required by AI safety standards.
    """
    disclaimer = "\n\n*Transparency Note: This recommendation was generated by CareerSetu AI based on industry skill models. Please verify prerequisites with your academic advisor or recruiter.*"
    if "*Transparency Note:" not in response:
        return response + disclaimer
    return response
